# Generated by Django 5.2.6 on 2025-10-10 09:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_remove_survey_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True, unique=False),
        ),
    ]
