# Generated by Django 5.2.6 on 2025-10-10 09:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_auto_20251010_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
