# Generated by Django 5.2.6 on 2025-10-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_question_likertquestion_multichoicequestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(default='null', editable=False, max_length=25),
            preserve_default=False,
        ),
    ]
