# Generated by Django 5.2.6 on 2025-10-10 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_question_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='name',
        ),
    ]
