# Generated by Django 5.2.6 on 2025-11-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_remove_question_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likertquestion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='multichoicequestion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.RemoveField(
            model_name='question',
            name='polymorphic_ctype',
        ),
        migrations.AddField(
            model_name='survey',
            name='anonymous_responses',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='shuffle_questions',
            field=models.BooleanField(default=False),
        ),
    ]
