# Generated by Django 5.2.6 on 2025-11-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0015_remove_survey_questions_question_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='required_question_feilds',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='question_count',
            field=models.IntegerField(default=0),
        ),
    ]
