# Generated by Django 5.2.6 on 2025-11-14 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_question_required_question_feilds_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='required_question_feilds',
        ),
    ]
