# Generated by Django 5.2.6 on 2025-11-14 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('survey', '0017_remove_question_required_question_feilds'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likertquestion',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='multichoicequestion',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='question',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
    ]
