# Generated by Django 5.2.6 on 2025-11-15 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0019_response_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='value',
        ),
        migrations.RemoveField(
            model_name='response',
            name='uuid',
        ),
        migrations.AddField(
            model_name='response',
            name='completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='response',
            name='respondent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
