# Generated by Django 5.2.6 on 2025-11-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0020_alter_response_options_remove_answer_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
