# Generated by Django 5.2.6 on 2025-11-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0021_answer_answer_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likertquestion',
            name='scale_min',
        ),
        migrations.AddField(
            model_name='likertquestion',
            name='reverse_scale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='likertquestion',
            name='scale_max',
            field=models.IntegerField(default=3, help_text='Max value must be positive (min is always 1).'),
        ),
    ]
