# Generated by Django 5.2.6 on 2025-11-16 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0022_remove_likertquestion_scale_min_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likertquestion',
            name='reverse_scale',
        ),
    ]
