# Generated by Django 5.2.6 on 2025-11-17 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0023_remove_likertquestion_reverse_scale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likertquestion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='multichoicequestion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.RemoveField(
            model_name='question',
            name='polymorphic_ctype',
        ),
    ]
