# Generated by Django 5.2.6 on 2025-11-17 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('survey', '0024_alter_likertquestion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likertquestion',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='multichoicequestion',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='multichoicequestion',
            name='the_minimum_number_of_options_to_be_selected',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='multichoicequestion',
            name='options',
            field=models.JSONField(default='[]'),
        ),
    ]
