# Generated by Django 5.2.6 on 2025-11-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0025_alter_likertquestion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likertquestion',
            name='scale_labels',
        ),
        migrations.AddField(
            model_name='likertquestion',
            name='options',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='multichoicequestion',
            name='options',
            field=models.JSONField(default=list),
        ),
    ]
