# Generated by Django 5.2.6 on 2025-11-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0026_remove_likertquestion_scale_labels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multichoicequestion',
            name='the_minimum_number_of_options_to_be_selected',
            field=models.IntegerField(default=1),
        ),
    ]
