# Generated by Django 5.2.6 on 2025-11-21 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0022_alter_answer_question'),
        ('survey', '0028_remove_likertquestion_scale_max'),
    ]

    operations = [
    ]
