# Generated by Django 5.2.6 on 2025-11-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0029_merge_20251121_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='likertquestion',
            name='scale_max',
            field=models.IntegerField(default=5),
        ),
    ]
