# Generated by Django 5.2.6 on 2025-12-23 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0030_likertquestion_scale_max'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrixQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey.question')),
                ('rows', models.JSONField(blank=True, default=list)),
                ('columns', models.JSONField(blank=True, default=list)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('survey.question',),
        ),
    ]
