# Generated by Django 5.2.6 on 2025-12-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0031_matrixquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrixquestion',
            name='columns',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='matrixquestion',
            name='rows',
            field=models.JSONField(default=list),
        ),
    ]
