# Generated by Django 5.2.6 on 2026-01-15 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0033_ratingquestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['position']},
        ),
    ]
