# Generated by Django 5.2.6 on 2026-01-31 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0038_answer_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['position'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'verbose_name': 'Survey', 'verbose_name_plural': 'Surveys'},
        ),
        migrations.AlterField(
            model_name='likertquestion',
            name='options',
            field=models.JSONField(default=list, verbose_name='Options'),
        ),
        migrations.AlterField(
            model_name='likertquestion',
            name='scale_max',
            field=models.IntegerField(default=5, verbose_name='Scale Max'),
        ),
        migrations.AlterField(
            model_name='matrixquestion',
            name='columns',
            field=models.JSONField(default=list, verbose_name='Columns'),
        ),
        migrations.AlterField(
            model_name='matrixquestion',
            name='rows',
            field=models.JSONField(default=list, verbose_name='Rows'),
        ),
        migrations.AlterField(
            model_name='multichoicequestion',
            name='allow_multiple',
            field=models.BooleanField(default=True, verbose_name='Allow Multiple'),
        ),
        migrations.AlterField(
            model_name='multichoicequestion',
            name='options',
            field=models.JSONField(default=list, verbose_name='Options'),
        ),
        migrations.AlterField(
            model_name='multichoicequestion',
            name='randomize_options',
            field=models.BooleanField(default=False, verbose_name='Randomize Options'),
        ),
        migrations.AlterField(
            model_name='multichoicequestion',
            name='show_as_dropdown',
            field=models.BooleanField(default=False, verbose_name='Show as Dropdown'),
        ),
        migrations.AlterField(
            model_name='multichoicequestion',
            name='show_as_rank_Question',
            field=models.BooleanField(default=False, verbose_name='Show as Rank Question'),
        ),
        migrations.AlterField(
            model_name='multichoicequestion',
            name='the_minimum_number_of_options_to_be_selected',
            field=models.IntegerField(default=1, verbose_name='Minimum Options to Select'),
        ),
        migrations.AlterField(
            model_name='question',
            name='helper_text',
            field=models.TextField(blank=True, null=True, verbose_name='Helper Text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='label',
            field=models.TextField(verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='question',
            name='position',
            field=models.IntegerField(verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=False, verbose_name='Required'),
        ),
        migrations.AlterField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.survey', verbose_name='Survey'),
        ),
        migrations.AlterField(
            model_name='rankquestion',
            name='options',
            field=models.JSONField(default=list, verbose_name='Options'),
        ),
        migrations.AlterField(
            model_name='ratingquestion',
            name='max_label',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Max Label'),
        ),
        migrations.AlterField(
            model_name='ratingquestion',
            name='min_label',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Min Label'),
        ),
        migrations.AlterField(
            model_name='ratingquestion',
            name='range_max',
            field=models.IntegerField(default=5, verbose_name='Range Max'),
        ),
        migrations.AlterField(
            model_name='ratingquestion',
            name='range_min',
            field=models.IntegerField(default=1, verbose_name='Range Min'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='anonymous_responses',
            field=models.BooleanField(default=False, verbose_name='Anonymous Responses'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='question_count',
            field=models.IntegerField(default=0, verbose_name='Question Count'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='shuffle_questions',
            field=models.BooleanField(default=False, verbose_name='Shuffle Questions'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='textquestion',
            name='is_long_answer',
            field=models.BooleanField(default=False, verbose_name='Is Long Answer'),
        ),
        migrations.AlterField(
            model_name='textquestion',
            name='max_length',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximum Length'),
        ),
        migrations.AlterField(
            model_name='textquestion',
            name='min_length',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minimum Length'),
        ),
    ]
