# Generated by Django 5.2.6 on 2026-02-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0039_alter_question_options_alter_survey_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='View Count'),
        ),
    ]
