# Generated by Django 5.2.6 on 2026-02-04 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0040_survey_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='section',
        ),
    ]
