# Generated by Django 5.2.6 on 2026-02-04 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0041_remove_answer_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likertquestion',
            name='scale_max',
        ),
    ]
